development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: bugzilla_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: bugzilla_test
  pool: 5
  username: postgres
  password: postgres